---
- name: Create Ubuntu User
  become: yes
  become_method: enable
  hosts: all
  
  tasks:
  
   - name: Create Ubuntu user 'danny' with specific uid and primary group of 'sudo'
     ansible.builtin.user:
       name: danny
       comment: Creating user "danny"
       uid: 1000
       group: sudo
       password: '$6$hzO9QgF8lSExriG$a71PwjQKREVmKasixZUMmTvceLRqsKdTFBK4sMS3//1sxUvzkHX9sE7vfzawMg5rsIOZLdyrW1wb3B2MsCxWu.'
       createhome: yes                    #Defaults to yes
       home: /home/danny                    #Defaults to /home/<username>

   - name: Remove user 'test' from all machines
     ansible.builtin.user:
       name: test
       state: absent
       remove: yes
