---
- name: Create Ubuntu User and SSH Keys
  become: yes
  become_method: enable
  hosts: all
  
  tasks:
  
   - name: Create Ubuntu User
     ansible.builtin.user:
       name: dan
       comment: Creating user "dan"
       uid: 1000
       group: sudo
