---
- name: Create Ubuntu User
  become: yes
  become_method: enable
  hosts: all
  
  tasks:
  
   - name: Create Ubuntu user 'dan' with specific uid and primary group of 'sudo'
     ansible.builtin.user:
       name: dan
       comment: Creating user "dan"
       uid: 1000
       group: sudo
       password: '$6$hzO9QgF8lSExriG$a71PwjQKREVmKasixZUMmTvceLRqsKdTFBK4sMS3//1sxUvzkHX9sE7vfzawMg5rsIOZLdyrW1wb3B2MsCxWu.'
       createhome: yes                    #Defaults to yes
       home: /home/dan                    #Defaults to /home/<username>

   - name: Add SSH key to 'dan'
     authorized_key:
       user: dan
       state: present
       key: "{{}lookup('file',pub_key)}"

   - name: Remove user 'test' from all machines
     ansible.builtin.user:
       name: test
       state: absent
       remove: yes